package models;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by julian on 10/11/17.
 */
public class SubtitlesCollection {
    public List<String> canBeAnnotated;   // List of subtitles files that we can process
    public List<String> wasAnnotated;     // List of subtitles previously generated by us

    public SubtitlesCollection() {
        canBeAnnotated = new ArrayList<String>();
        wasAnnotated = new ArrayList<String>();
    }
    public boolean isEmpty() { return canBeAnnotated.size() == 0 && wasAnnotated.size() == 0; }
}
